### ISSUE TITLE
Provide an object-oriented menu system #44

### ISSUE THREAD

**Issue by ghost** [cdotyone/mochaui#1]
Reported by gravydish, Jul 28, 2008

This is some code I've written for MochaUI to allow for dynamic menu 
modifications. This is likely not the right place for this, but I did not 
find your (Greg Houston's) email address to mail you directly (most likely 
due in part to my laziness).

Using the code works kinda like this:

MochaUI.RootMenu = new MochaUI.RootMenu();
MochaUI.RootMenu.merge({  
    'Start': {
    '>': {
        'Widget: Clock': {
            onClick: lib.clockWindow,
            id: 'clockLinkCheck'
        },
        'Widget: Mario Kart': {
            onClick: lib.marioKart,
            id: 'mario-kartLinkCheck'
        },
        'Login': {
            divider: true,
            onClick: lib.startLogin
        },
        'Logout': {}
    }}
});

This would render a menu like the following:

,-+---------------------+---------------/\/\
| | Start               |
`-+---------------------+-----------------------\/\
  | Widget: Clock       |
  | Widget: Mario Kart  |
  | ------------------- |
  | Login               |
  | Logout              |
`---------------------'

Nothing special is done behind the scenes. It renders HTML exactly the 
same as what is found in the index.html file. It just does it dynamically 
with MooTools.

The menu could be stored in a separate JSON file and included dynamically 
or could be included in-line as in the above example.

The merge() method supports alterations as well as additions. For example, 
executing this code after the above would cleanly (visually) remove the 
Login menu item:

MochaUI.RootMenu.merge({
    'Start': {
    '>': {
        Login: null,
        Logout: { divider: true }
    }}
});

You don't have to re-give the options you don't intend to change. Also, 
setting a menu item to 'null' inidicates that you wish to remove it 
completely.

Perhaps the code could be better written to make assumptions on the sub 
menus and not require them to be placed under a special '>' key, but it 
seems intuitive to read as it is written above.

Lastly, for small changes, a static forPath() method exists:

MochaUI.MenuItem.forPath('/Start/Login').set('enabled',false);

would disable the 'Login' menu item under the 'Start' menu.

The code makes the assumption that the developer would want to use the 
global name MochaUI.RootMenu for the root menu variable after the example 
of many other MochaUI components; however, a simple variable (var root, 
for instance) is fully supported so that more than one menu could exist at 
the same time. In this case, the above code would change to:

MochaUI.MenuItem.forPath('/Start/Login', root).set('enabled',false);

I wanted mainly to post my work here to see if there is any interest. If 
so, I could provide a better example (with an HTML file, etc). I didn't 
want to waste the time if the MochaUI developers are not interested in 
this type of approach.

What version of the product are you using? On what operating system?
MochaUI 0.9 Beta, Windows
Code has been tested with IE6 and Opera 9.50 on Windows XP only; however, 
the code uses MooTools 1.2 exclusively and so should be compatible with 
any browser MooTools 1.2 is compatible with.

```
mocha-menu.js
```

10.9 KB   Download
Comment 1 by gravydish, Jul 28, 2008

Mario kart widget is derived from the canvas/javascript experiment: http://
blog.nihilogic.dk/2008/05/javascript-super-mario-kart.html

Comment 2 by gregory.houston, Jul 28, 2008

This looks great. I would probably put this at source/Window/Menu.js

Will you do a couple things:
1. Format the comments like in source/Window/Window.js. This will make it so your
   comments can be parsed by Natural Docs and thus added to the Mocha UI documentation.
   Tabs, naming, and so forth need to be like in Window.js for the parsing to work.
   "@param options" for example needs to be "Options:". The extra asterisks on the left
   side of your comments should be removed. 

All the Mocha UI documentation comes from the javascript files so it is a good idea
to add some of the above instructions and examples to the javascript file. Note the
(start code) and (end) tags in the Window.js examples. 
1. Make an example html page. Since mocha-init.js is already being used for the main
   demo, will you put the javascript that initializes the menu in the head tag of the
   example page. See no-toolbars.html for an example.

Thanks, and this is a great place to submit features like this. This way it is
documented and I won't forget about it.    

Labels: -Type-Defect Type-Enhancement
Comment 3 by gravydish, Jul 29, 2008

Greg,

I deviated from your requests in a couple ways...

Personally, I feel that remaking the mocha-init.js file with dynamic menu items 
makes it more structured and approachable. It also groups the code for menu click 
events with the menu items themselves. I've included the remade index.html and mocha-
init.js files along with a newer version of the mocha-menu.js file (including a 
couple of bug fixes I've come across). Also, I condensed a couple of the menu click 
event routines (for the clock, for instance), because they did not appear to work in 
stock MooTools 1.2. I've used the Asset.javascript() method which apparently has a 
bug for Opera 9.50 -- and I noticed you've already posted a bug for that.

The dynamic menu appears to look and function equivalently for me on IE6 and Opera 
9.50. It at least serves as a better example for you of how I'm using it. For 
whatever reason, the version of MooTools that is shipped with MochaUI 0.9 does not 
work with the mocha-menu.js script I've written. You'll see in the index.html file, 
I'm including MooTools 1.2 'core' and 'more' files as I have them named on my 
machine. You may need to adjust as necessary.

I feel that including the dynamic menu in the main demo would be really sweet, if, 
for instance, in the Tools menu you simply gave access to a tool like the Window 
Parametrics or Window Builder to dork around with the menu itself and example how 
dynamic it could be.

Also, the documentation for Natural Doc explains that leaving asterisks in your 
comments is supported. I personally feel that asterisks make the code documentation 
inside class declarations easier to read. I understand the importance and 
significance of consistency, and I most assuredly don't mind removing the asterisks 
for your version, but I feel I would like the keep the asterisks for my version. The 
version I've included here still includes the asterisks. Please elaborate on your 
feelings there.

I am also unaware of how to document the MochaUI.MenuItem.forPath() static method 
which is defined outside the class. I gave it my best shot with a namespace operator 
(::).

Please understand I don't mean to be controlling or overbearing. I really appreciate 
what you've done and am excited about contributing a small portion.

```
mocha-init.js
```

19.5 KB   Download
    index.html
2.3 KB   Download
    mocha-menu.js
17.1 KB   Download
Comment 4 by gregory.houston, Jul 29, 2008

The latest available version of 0.9 comes with Mootools 1.2 'core' and 'more'.

I definitely want to keep the commenting style consistent from one file to another.

Since you want to add your feature set to the main demo it will have to wait until I
have a chance to work on Mocha UI again and can review this. That could be a few
months. I'm not sure how much more I want to complicate the demo. As it's own example
page however I could probably add it to the SVN within a week as long as it works in
all the browsers supported by Mocha UI.

It would be good if you tested in IE7, Firefox 2 and 3. If you don't have a Mac I can
test it in Safari and Mac Firefox. Even with the Mootools abstraction layer it is
actually pretty rare that new code immediately works in all the A-Class browsers
without a little tweaking.

Regarding, MochaUI.MenuItem.forPath(), I don't know what this is but keep in mind
that functions or classes that the user will not directly use should not be commented
in such a way that they will show up in Natural Docs. Notice that there are many
times more comments in source/Window/Window.js than what you see in the documents.
All those extra comments are for people actually modifying the code. They are not
meant to be seen by the end user in the documentation because it would just confuse
them and not really benefit them in anyway.

// ... if in the Tools menu you simply gave access to a tool like the Window 
// Parametrics or Window Builder to dork around with the menu itself and example how 
// dynamic it could be.

Please feel free to make a plugin for this. Both the Parametrics and the Window
Builder you mention are in mocha/plugins/

G.

Comment 5 by gravydish, Nov 17, 2008

I like the work you've done with MochaUI 0.9.5!

I've added context (popup) menu support into the dynamic menu library along with a 
couple of other bug fixed. I am going to try and write a demo plugin for 0.9.5 this 
week and post the new code and plugin.

Comment 6 by mfuery, Nov 25, 2008

Nice work guys!  This will come in very handy in my current app I'm working on at work.

**Comment by mui-org** [comment]
already done by greg
