### ISSUE TITLE
Youtube video restarts when in Iframe and redocked. - #70

### ISSUE THREAD

**Issue by ghost** [cdotyone/mochaui#10]
Reported by ged...@gmail.com, May 28, 2009

What steps will reproduce the problem?
1. Open a panel with YouTube Player in it
2. Press play
3. Drag to a new docking position

What is the expected output? What do you see instead?
Expect it to just keep playing.
Instead it restarts.

What version of MochaUI are you using?
Trunk. R 527

On what operating system and with what browser?
Chrome, Vista

Please provide any additional information below.

**Comment by mui-org** [comment]
happens on firefox also.  not sure if this has anything todo with mocha ui. mochui uses mootools and flash to handle the youtube.  I have looked at the code and can't see how mootools is responsible for this.
