### ISSUE TITLE
Asset.css conflict with mootools standard Asset

### ISSUE THREAD

**Issue by partikule** [cdotyone/mochaui#102]
When using another script which use Asset.css, the extended one created in require.js generated a conflict : 

properties.onload is not a function

**Comment by partikule** [comment]
Found a solution : 

In require.js, line 160, replace : 
 `properties.onload();`

by : 
 `if (typeOf(properties.onload) == 'function') properties.onload();`

**Comment by cdotyone** [comment]
Accepting this code for now.
-Chris
