### ISSUE TITLE
Send HTML to a modal (no request)

### ISSUE THREAD

**Issue by partikule** [cdotyone/mochaui#105]
When setting HTML content to a modal, the content isn't displayed.

Basically, what I do :
 <pre>
// Creation of the HTML content... More complete in the real world :-)
var wMessage = new Element('div', {'class':'message'}).set('text', 'This is my user message');
var wContent = new Element('div').adopt(wMessage);

// I set my options
var options = {
    id: 'wdelconfirm0',
    content: wContent,
    title: 'The window title',
    cssClass:'confirmation',
    draggable: true,
    padding: { top: 15, right: 15, bottom: 8, left: 15 }  
}
// Modal creation
new MUI.Modal(options);
</pre>

The problem is in <strong>window.js</strong> line 1141, the type of the content option is 'element', so the switch case will be 'default' and the content is pushed to the sections array. :

<pre>
switch (typeOf(options.content)){
    case 'string':
        // was passed html, so make sure it is added
        this.sections.push({
            loadMethod:'html',
            content:options.content
        });
        break;
    case 'array':
        this.sections = options.content;
        break;
    default:
        /*
        * <strong>HTML Element will be considered here....not correct</strong>
        */
        this.sections.push(options.content);
}
</pre>

<strong>Proposed solution : </strong>

<pre>
switch (typeOf(options.content)){
    case 'string':
    <strong>case 'element':</strong>
        /*
        * <strong>HTML Element will now be considered here....</strong>
        */
        // was passed html, so make sure it is added
        this.sections.push({
            loadMethod:'html',
            content:options.content
        });
        break;
    case 'array':
        this.sections = options.content;
        break;
    default:
        this.sections.push(options.content);
}
</pre>

**Comment by cdotyone** [comment]
Thanks for the fix.

**Comment by cdotyone** [comment]
Code added to develop branch.
