### ISSUE TITLE
window.resize() "centered" option correction

### ISSUE THREAD

**Issue by partikule** [cdotyone/mochaui#106]
Symptom : When using resize() on a window from an external call, with "centered" option to true and just the "top" option set (for exemple) the window isn't centered correctly.

Reason : The type of options.top, options.left is not detected correctly.

Correction : 
In <strong>window.js</strong>, function <strong>resize</strong>, replace : 

<pre>
        if (options.centered){
            top = typeof(options.top) != 'undefined' ? options.top : oldTop - ((options.height - oldHeight) * .5);
            left = typeof(options.left) != 'undefined' ? options.left : oldLeft - ((options.width - oldWidth) * .5);
        } else {
            top = typeof(options.top) != 'undefined' ? options.top : oldTop;
            left = typeof(options.left) != 'undefined' ? options.left : oldLeft;
        }
</pre>

by :

<pre>
        if (options.centered){
            top = typeOf(options.top) != 'null' ? options.top : oldTop - ((options.height - oldHeight) * .5);
            left = typeOf(options.left) != 'null' ? options.left : oldLeft - ((options.width - oldWidth) * .5);
        } else {
            top = typeOf(options.top) != 'null' ? options.top : oldTop;
            left = typeOf(options.left) != 'null' ? options.left : oldLeft;
        }
</pre>

**Comment by cdotyone** [comment]
Will look into this. Thanks for the fix.

**Comment by cdotyone** [comment]
Added to develop branch. Thanks for code.
