### ISSUE TITLE
collapse panels in demo (demo/index.html) croaks: MUI.get() on panel.id which is ""

### ISSUE THREAD

**Issue by GerHobbelt** [cdotyone/mochaui#113]
cause: mocha has a Sortables for columns: this one clones the DOM on start (click) and the clone gets all its 'id' attributes wiped (mootools: cleanClone()).
The regular click handler (when clicking on the collapse/expand buttons in the panel toolbars) apparently delivers these clones in the 'panel' variables, thus breaking the code in several places.

A temporary 'workaround' is to set Controls/column.js options.sortable to FALSE. (losing you the sortable ~ reordering functionality for panels in a column)

**Comment by GerHobbelt** [comment]
:-(  demo/index.html is not in HEAD; a fork/merge mismatch on my side. Nevertheless, went and tested with the 'official' Demo/demo-application-html.html and same issue (and work-around) there.

FF4 / Safari 5 on Win7/64

**Comment by cdotyone** [comment]
As you stated the drag events where cloning while collapsing/expanding.  I took care of this in previous path within the last week.  It is in the most current develop branch.
-Chris
