### ISSUE TITLE
specifying multiple plugins for mochaUI would not load all of those, just the last one

### ISSUE THREAD

**Issue by GerHobbelt** [cdotyone/mochaui#115]
calls like these fail to load all the plugins:

MUI.load(['Parametrics','famfamfam','CoolClock']);

for a fix, see
https://github.com/GerHobbelt/mochaui/commit/47f804cca918cd939bae621c8a0d9a2c85848ca8

**Comment by cdotyone** [comment]
Thanks, for the patch.  Added to develop branch.
-Chris
