### ISSUE TITLE
Shake & IE9

### ISSUE THREAD

**Issue by StephenSegari** [cdotyone/mochaui#118]
The shake method errors out with Mootools 1.3.2 and MochaUI 0.9.7.

Line 628 of Core.js seems to be the culprit:

var morph = this.get('morph',{
            duration:50,
            link:'chain'
        });

**Comment by cdotyone** [comment]
I will not be updating 0.9.7 branches for IE9 compatibility.  Provided patches will be added if submitted.
-Chris
