### ISSUE TITLE
MochaUI and MapGuide Fusion problem

### ISSUE THREAD

**Issue by mconte79** [cdotyone/mochaui#121]
Hi,
my web application works with MochaUI and MapGuide Fusion( MapGuide Fusion in based on JxLib). All works fine except when I try to draw a new object. The object rendering don't work fine. In Firefox the rendering works with graphic errors but in IE,Chrome and Safari you don't see anything. Both framework used Mootools and canvas library. May be a problem of conflicts? How I can resolve it?
Regards
Matteo

**Comment by cdotyone** [comment]
Not an issue with mocha use Google groups for this type of support.  Canvas not needed for IE9.  Moving away from canvas use.
