### ISSUE TITLE
Menu structure

### ISSUE THREAD

**Issue by BuenGenio** [cdotyone/mochaui#125]
Is it still possible to initialize the menu from an unordered list? e.g. 

<ul id="menu">
<li>File<ul>
                    <li><a id="Open" href="#">Open</a>
....

**Comment by mui-org** [comment]
At the moment no, but I may add back in.  The goal is to be completely JSON based.  Any HTML support will only be there for backwards compatibility unless someone else steps up to carry that feature.
-Chris

**Comment by mui-org** [comment]
added back in, needed for virtual desktop demo.
