### ISSUE TITLE
taskbar.js mismatch on CSS rule className 

### ISSUE THREAD

**Issue by DimitarChristoff** [cdotyone/mochaui#128]
https://github.com/DimitarChristoff/mochaui/blob/develop/Source/Controls/taskbar/taskbar.js#L103
https://github.com/DimitarChristoff/mochaui/blob/develop/Source/Controls/taskbar/taskbar.js#L107
https://github.com/DimitarChristoff/mochaui/blob/develop/Source/Controls/taskbar/taskbar.js#L111

results in null value for the taskbar buttons colours as the CSS has been refactored to use different classNames:

https://github.com/DimitarChristoff/mochaui/blob/develop/Source/Themes/default/css/taskbar.css#L109-120

fix: apply namespace to the css classes
better fix: define class names in options with default values for colours, should it fail. Separation of concerns, lacks degradation, reliance on CSS declarations alone is flaky.

**Comment by mui-org** [comment]
Yep picked that seperately, should be ok now.

-Chris
