### ISSUE TITLE
Safari4 maximize window error - #73

### ISSUE THREAD

**Issue by ghost** [cdotyone/mochaui#13]
Reported by fblomqvist, Jun 16, 2009

What steps will reproduce the problem?
1. Open the Demo
2. Open the "Ajax/XHR Demo", "Split window" or "Iframe: Youtube" window
3. click maximize window

What is the expected output? What do you see instead?
Window should be maximized.
Nothing happens and the window can't be dragged anymore (though it can be
closed)

What version of MochaUI are you using?
Current SVN version (June 16:th)

On what operating system and with what browser?
Win Vista and XP. Safari4

Please provide any additional information below.
This errors shows up in the error console:
"TypeError: Result of expression
'this.windowEl.getElements('.handle').hide' [undefined] is not a function."
Thrown from the detachResizable() in Window.js

Regards
// Fredrik Blomqvist

**Comment by mui-org** [comment]
no longer a problem
