### ISSUE TITLE
the official website can't open

### ISSUE THREAD

**Issue by kolabell** [cdotyone/mochaui#133]
www.mochaui.org can not open now, I want to know what's the problem.I want to see the api and docs about mocha-ui.

**Comment by patrizi** [comment]
In meanwhile, there is another place where found the mocha-ui's documentation ?

**Comment by nachiket-p** [comment]
@patrizi checkout source code, there is Docs folder .. 
I think it is having all the documentation.you can see it in github too.. 
see this link..
https://github.com/mui/mochaui/blob/develop/Docs/Core/Panel.md

@cdotyone Any plans for MochaUI? Awaiting for 1.0 version.

**Comment by patrizi** [comment]
Yes, thanks ! 
Sorry, I don't see it before ...
