### ISSUE TITLE
Dock.js ignores initialization options - #77

### ISSUE THREAD

**Issue by ghost** [cdotyone/mochaui#17]
Reported by noeldacosta, Jul 20, 2009

What steps will reproduce the problem?
1. function(){MUI.Dock.initialize({'useControls':false});},
2.
3.

What is the expected output? What do you see instead?
MUI.Dock is ignoring any options that are passed as arguments to the initialize function and 
instead always uses those hard-coded options within dock.js itself. So with the above 
initialisation string, it should hide the dock controls, but it doesn't.

What version of MochaUI are you using?
0.9.6 development

On what operating system and with what browser?
Mac OS X leopard and firefox 3

Please provide any additional information below.
I'm used this implemented by making Dock an extension of the Mootools Class native, which 
gives it the setOptions() method. Along these lines..

MUI.Dock = new Class({

```
Implements:Options,

options: {
    useControls:          true,      // Toggles autohide and dock placement controls.
    dockPosition:         'bottom',  // Position the dock starts in, top or bottom.
    // Style options
    trueButtonColor:      [70, 245, 70],     // Color for autohide on
    enabledButtonColor:   [115, 153, 191], 
    disabledButtonColor:  [170, 170, 170]
},

initialize: function(options){

    this.setOptions(options);
```

...

...
});

**Comment by mui-org** [comment]
created setOptions for dock
