### ISSUE TITLE
Compatability Issue with MooTools 1.2.3 - #78

### ISSUE THREAD

**Issue by ghost** [cdotyone/mochaui#18]
Reported by i...@maniahub.com, Aug 24, 2009

What steps will reproduce the problem?
1. Updating MooTools core and more files to latest version downloadable 
from MooTools website.
2.
3.

What is the expected output? What do you see instead?
Windows loading using the normal examples are expected. Instead no windows 
are loaded at all and an error occurs.

What version of MochaUI are you using?
0.9.5

On what operating system and with what browser?
Windows Vista Ultimate - Chrome 2.0.172.39 & Internet Explorer 
8.0.6001.18813

Please provide any additional information below.

**Comment by mui-org** [comment]
works with 1.2.4
