### ISSUE TITLE
scrollbar handle doesn't scale down enough - #79

### ISSUE THREAD

**Issue by ghost** [cdotyone/mochaui#19]
Reported by corn13read, Aug 25, 2009

when resizing some of the panels the scrollbar drag doesn't resize down
beyond a certain point and it gets to the point where you have to use the
up or down arrow instead.

Fantastic project! I hope to see future development.

**Comment by mui-org** [comment]
Scroll bars are controlled by browser.  I don't see the value in building anything to take care of this case.
