### ISSUE TITLE
closeColumn doesn't close panels - #82

### ISSUE THREAD

**Issue by ghost** [cdotyone/mochaui#22]
Reported by fblomqvist, Sep 28, 2009

What steps will reproduce the problem?
1. create a column and a panel
2. close the column using closeColumn()

What is the expected output? What do you see instead?
column should be closed including the panel inside it. 
It _looks_ like the panel is being closed but only because the DOM is
removed. The code inside closeColumn that should call closePanel uses and
incorrect selector and thus closePanel is never called.

What version of MochaUI are you using?
Current SVN.

On what operating system and with what browser?
Win Vista, FF3

Please provide any additional information below.
Actually a second error in closeColumn in the case of sortable columns.
#1431 uses "instance.container" instead of "instance.options.container".

Comment 1 by fblomqvist, Oct 13, 2009

Another observation could be that closePanel should close any containing columns.
A fully generic version of close should traverse the full tree of containing elements
and close them bottom-up. (also for window.close).

**Comment by mui-org** [comment]
Would like to get rid of all control specific close.  ie. closePanel, closeColumn, and give all controls a simple close method.  That way they can be chained together.

**Comment by mui-org** [comment]
breaking this into two separate tasks.  one to fix current closeColumn, and another task to create a generic close for all mochaui controls
