### ISSUE TITLE
Calendar plugin on a MODAL window - #85

### ISSUE THREAD

**Issue by ghost** [cdotyone/mochaui#25]
Reported by alpmatari, Nov 10, 2009

What steps will reproduce the problem?
1. Add the plugin in a modal window with a form.

What is the expected output? What do you see instead?
I expect to see the calendar, but I don't see it. It is behind the modal
window. I've change the z-Index property in the CSS calendar but it doesn't
work.

What version of MochaUI are you using? If you are using a copy of MochaUI
from the SVN, what revision number are you working with?
I'm using the last development version downloaded by HTTP.

On what operating system and with what browser?
Windows XP / Firefox 3.5.1

Please use labels and text to provide additional information.
I move the modal window and see the calendar behind. It works perfect: I
select a date and set it into the form field. 

```
Calendar-issue.png
```

206 KB   View   Download

**Comment by mui-org** [comment]
fixed z-index in calendar plugin
