### ISSUE TITLE
reset of css top property if a window is dragged "too high" - #90

### ISSUE THREAD

**Issue by ghost** [cdotyone/mochaui#30]
Reported by luca.boccianti, Jan 14, 2010

What does your patch do?

if a window with no limitation on dragging is dragged "too high" so that
when the user release the mouse button then the user can't drag it back,
then the window top css property is set to a value that make it draggable
again.

What version of MochaUI is it for and what revision number in the SVN?

0.9.5

What files were changed?

mocha.js

What browsers have you tested it in?

windows vista:
firefox 3.5.7
internet explorer 8
safari 4.0.4
chrome 3.0.195.38

ubuntu:
firefox 3.0.9

mac osX:
firefox 3.5.7
safari 4.0.4

I've modified internal function attachDraggable() in file mocha.js.  mine
start at line 1392.  

sorry for being pedantic in the comments but I tend to forget things.

```
/*

Internal Function: attachDraggable()
    Make window draggable.

Arguments:
    windowEl

*/
attachDraggable: function(windowEl){
    if (!this.options.draggable) return;
    this.windowDrag = new Drag.Move(windowEl, {
        handle: this.titleBarEl,
        container: this.options.restrict == true ? $(this.options.container) :
```

false,
            grid: this.options.draggableGrid,
            limit: this.options.draggableLimit,
            snap: this.options.draggableSnap,
            onStart: function() {
                if (this.options.type != 'modal' && this.options.type != 'modal2'){ 
                    MochaUI.focusWindow(windowEl);
                    $('windowUnderlay').setStyle('display','block');
                }
                if ( this.iframeEl )
                    this.iframeEl.setStyle('visibility', 'hidden');
            }.bind(this),
            onComplete: function() {
                if (this.options.type != 'modal' && this.options.type != 'modal2') {
                    $('windowUnderlay').setStyle('display', 'none');
                }
                if ( this.iframeEl ){
                    this.iframeEl.setStyle('visibility', 'visible');
                }
                // Store new position in options.
                this.saveValues();

```
            // ****************************
            // here my modifications start
```

// dragMinY is an optional parameter that can be added or not
// when setting the new MochaUI.window.  it represent the minimum
// px value you want to accept for the css top of your window.
// operator !== should be used because 0 is an acceptable value.

```
            if(this.options.dragMinY !== false) {
                var dragMinY = this.options.dragMinY;
                var ttop = $(this.options.id).getStyle('top');

                // we will obtain a *string* like "-100px", so we need to get rid of "px"
                ttop = ttop.replace('px', '');
                if(ttop < dragMinY) {
                    $(this.options.id).setStyle('top', dragMinY + 'px');
                }
            }
            // and that's all ************************

        }.bind(this)
    });
},
/*
```

an example of the use of such new parameter:

new MochaUI.Window({
  id: 'myMochaUIWindow',
  title: 'my title',
  loadMethod: 'xhr',
  contentURL: 'index.php?myparam=something&'+new Date().getTime(),
  y: 120,
  //here, here!
  dragMinY: 0,
}

with some easy modifications one could set different parameters for the y
coord at which repositionate the window and the actual repositioning, say
that when the css top goes below zero reset it at 60px.

**Comment by mui-org** [comment]
can not drag window outside of viewport anymore, not a problem currently
