### ISSUE TITLE
generic close for all elements

### ISSUE THREAD

**Issue by mui-org** [cdotyone/mochaui#35]
create a generic way to close a panel, window, or column

**Comment by mui-org** [comment]
this has been added to version 0.9.8

**Comment by eerne** [comment]
Sorry to comment in closed issues:

Could we add the MUI.close() again? See discussion: http://groups.google.com/group/mocha-ui/browse_thread/thread/15ccdaa1fb5ff969

In this solution just takes an element and calls .close() on it. Would be great for backwards comitablityl, though I have only tested with windows.
http://github.com/eerne/mochaui/commit/ef8999569d72c3d0a4f71b7d3b3a99c288b8be7c
(This was my only merge conflict)

**Comment by mui-org** [comment]
I prefer MUI.get('window').close();  I am supporting $('window').close() for panels, columns, and windows only.   It actually used to be MUI.closePanel(), MUI.closeWindow etc.  I really hated that.

In the long run I am trying to eliminate as much as I can from MUI.  I don't like a lot of unrelated function calls being added to MUI.  This creates chaos long term.  The cleaner approach is to push the functionality down into the individual classes.
