### ISSUE TITLE
onContentLoaded should be called on panel/window update

### ISSUE THREAD

**Issue by almoehi** [cdotyone/mochaui#36]
Hi !
the onContentLoaded callback of a panel/window doesn't get called if you perform a MUI.updateContent() on them.
e.g.
new MUI.Panel({
  id: 'myPanel',
  onContentLoaded: function(){ alert('called!'); }
});
MUI.updateContent({element: 'myPanel'});

should alert 'called'
I think this is a general issue. But especially if you do tab-switching which also uses the updateContent within the initializeTabs function to load the appropriate tab content.

greetings

**Comment by mui-org** [comment]
http://github.com/downloads/cdotyone/mochaui/mochaui-0.9.7-RC2.zip - should fix this problem

**Comment by almoehi** [comment]
yep, seems to work.
thanks!
