### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by stodge** [cdotyone/mochaui#37]
I get an error with Chrome on Linux when viewing index.html:

Uncaught TypeError: Cannot read property 'length' of null        script/mocha.js line 700

**Comment by mui-org** [comment]
When I opened MochaUI with Chrome 5.0.375.55 it worked.  What version are you using?  Did you have to do anything to make the error appear, or did it happen on load?

**Comment by stodge** [comment]
Ah sorry - I realised I was loading it from the local drive instead of across the network. :P

**Comment by mui-org** [comment]
no problem
