### ISSUE TITLE
Use box-shadow and border-radius

### ISSUE THREAD

**Issue by eerne** [cdotyone/mochaui#39]
Just a thought, if a browser has box-shadow and border-radius it could use CSS for the Windows corner and shadow, if not it could use canvas fallback as it is currently. 

Should I give it a try?

**Comment by mui-org** [comment]
I prefer to have css do everything.  Eventually I will be try to remove an none css formatting options.   So go for it.

**Comment by mui-org** [comment]
you still plan on working this?

**Comment by eerne** [comment]
cdotyone I am not sure how to proceed with this one, currently there is options.useCanvas and options.useCanvasControls, both boolean.

How about I add shadow, gradient and radius to the No Canvas window and a new option (options.tryUseCSS3) that could fallback to canvas on IE6.

On certain Browsers (IE<9 and older FF) it could then fallback to just useCanvas (if true), does that sound reasonable?

**Comment by mui-org** [comment]
options.useCSS3 - defaults to true, fallback to useCanvas - with note on description + documentation.

We may move this option to MUI.options.useCSS3 if some other controls could benefit from CSS3.  I am not far enough along to make that call yet.  

In any case the default will be true and fallback to useCanvas and CSS2.

**Comment by eerne** [comment]
added options.useCSS3 and 3 tests "CSS3 Body", "CSS3 Fallback", "Force Canvas" and tested on Mac FireFox 3.6, Safari 4, Windows IE6 and IE8. Please test, especially if anyone has access to FireFox <= 3.5 or Safari < 4.

http://github.com/eerne/mochaui/commits/develop

On IE6 the window build even with the error (issue 48 'request' is null or not an object) but there is no content loaded inside the Window. All other browser seem ok so far.
