### ISSUE TITLE
"$extend(Asset..." and "Closing Jobs" problem

### ISSUE THREAD

**Issue by ss5** [cdotyone/mochaui#41]
Hi,
I hope this is the right place for this.
If not, feel free to delete this. Both problems are part of the mocha.js file.
I have noticed, that I have to comment out this part of the "$extend(asset..." function to make it work:

if ($(properties.id)) {
            properties.onload();
            return $(properties.id);
        }   

I am using Chrome 6.0.427.0 but I have used this "fix" for quite some time. I think Firefox also has problems with that part, if loading multiple assets at one go.

Also I noticed that in the "Closing Jobs" part the delay
"//added Delay to make sure window id is erased
(function() {instance.fireEvent('onCloseComplete'); }).delay(100);"
has been removed, which breaks my application (CloseComplete is probably not fired without it).

I am not a javascript expert - just wanted to let you know.

**Comment by mui-org** [comment]
on the asset loading problem.  not sure how to reproduce.  load more than one asset at a time?

second problem.  I do not have not issues adding the delay for you.

**Comment by ss5** [comment]
Ok, the asset loading problem is happening if I load several assets at a time like
this: 
['http://domain.com/swfupload/js/script1.js','http://domain.com/scripts/script2.js'],css: ['http://domain.com/swfupload/css/default.css'],...
Sometimes within these scripts I load some cotent via AJAX and more assets - that is when it fails (no error messages in the console).
And if I comment out the mentioned part it works on all browsers I have on my windows xp system (Firefox,Opera,Safari,Chrome,IE8).

**Comment by eerne** [comment]
Hi soundseller

I tested to load 10 more js scripts (each just with console.log(n); and a block of commetns) with todays git develop branch. I tested with require: [js:[]] in a MUI.Window. But I guess it doesn't matter if it is from window or a panel.

In my test it successfully prints number 1-10 then fires onload followed by onContentLoaded. This is Google Chrome, FireFox 3.6.4, Safari 5

Now for the case: when you load more scripts within these scripts, you will definitely have to setup your own onComplete callback.

This issue should be closed.

**Comment by ss5** [comment]
Hmm, why is everything working without:
if ($(properties.id)) {
        properties.onload();
        return $(properties.id);
    } 
?
What do you mean by "setting up my own onComplete callback"?
The scripts won't even start loading, so what's the point of a onComplete callback?
As mentioned above - I am just a hobbyist so please excuse my ignorance.

**Comment by eerne** [comment]
Don't worry, it's great that you report any issues you have with MochaUI. But I can't follow what is working for you and what not unless you provide an example. If it is a bug I'd like to track it down, so thanks for you report. The MUI.Require code is in Source/Core/Core.js, but I didn't find any "if ($(properties.id))".

In my test with the recent git develop branch, it loads several assets (as mentioned before), specified in require: [], then it fires both onload and onContentLoaded, so I can't see any problem there.

Are you using the latest git code?

Can you show the exact code how you try to load several assets, so we can reproduce the problem?

Maybe in a gist or pastie.org

**Comment by ss5** [comment]
I am currently using v. 0.9.7 and the part I am talking about is in mocha.js line number 887-890 or Core.js line number 862-865.
I just checked out the latest development branch and you are right, the whole thing seems to have gotten a complete re-write :)
So yes - this problem is probably obsolete.
I will try to implement the new version some time and will check, if the problem still exists.
Regards!
