### ISSUE TITLE
Datagrid integration

### ISSUE THREAD

**Issue by cleankod** [cdotyone/mochaui#44]
How about integrating a datagrid, for example omnigrid: http://www.omnisdata.com/omnigrid/ with mochaUI?

**Comment by eerne** [comment]
looks pretty but it is Creative Commons Attribution 3.0 Unported License

**Comment by adamXL** [comment]
I have already tried that, but the omnigrid was unable to be at height 100%, especially when window/panel is being resized. So I am looking forward to see omnigrid integrated with mocha.

**Comment by cleankod** [comment]
The author of this project is pretty communicative. I'm sure he would agree to begin integration when asked.

**Comment by eerne** [comment]
I tested on IE6 and IE8 and it works pretty well, my only concerns are it's written in mootools-1.2.1.js and the License would have to be MIT.

**Comment by mui-org** [comment]
Only MIT licensed code will be placed in MochaUI.

**Comment by msantic** [comment]
Hi all,

I'm author of Omnigrid and Adam kindly refer me to this chat. I really appreciate you guys talking about integrating Omnigrid into MochUI because it's really great UI lib.

Omnigrid is very active project because it's heavily used in www.GISCloud.com project. Version at official Omnigrid web site isn't newest(I fix many bugs and add few new features) and I just need find time to upload it. Also, it works on newest Mootools version.

Regarding licence, this is really not a big issue for me so if you want I can publish Omnigrid with less restrictive license.

Best regards,

Marko

**Comment by eerne** [comment]
Hi Marko

Personally I would like to see Omnigrid integrated in mochaui and released under MIT license.
Have you thought about putting it on github / mootools forge too?

Could Omnigrid run on the client side (without the php that serves the data)?

Thanks
Enrique

**Comment by msantic** [comment]
Hi,

I changed the Omnigrid licence to MIT.

I didn't think about putting on github but yes, why not.

Yes, Omnigrid can run on the client side but why you ask that, how do you mean to serve the data?

Best regards,

Marko

**Comment by mui-org** [comment]
Marko,

Thanks for the license change.  I will take a look at what is involved in intergrating Omnigrid.

-Chris

**Comment by mui-org** [comment]
Mark,

You mentioned above the latest code is not published.  How soon will you publish on github, or can we have a early copy of it?

-Chris

**Comment by msantic** [comment]
I just published latest code so now you can work on it. 

-Marko

**Comment by mui-org** [comment]
Thanks for a quick turnaround.
-Chris

**Comment by msantic** [comment]
No problem. The thing is that I really appreciate open source community and you guys so this is actually just a little thing from me.

**Comment by DavideArgellati** [comment]
Also tablegear is mit, the source is bit more complex but works fine

**Comment by cleankod** [comment]
Omnigrid is more complex and functional. In my opinion Omnigrid is much better solution.

**Comment by DavideArgellati** [comment]
Omnigrid it's great and maybe is more easy to integrate in mocha but for customization and data format i prefer tablegear. 
Mocha FTW

**Comment by mui-org** [comment]
I am staying with Omnigrid for now.  It was an easy fit.

**Comment by idiotgenius** [comment]
any news ?

**Comment by cdotyone** [comment]
I added modified version of OmniGrid.  It was modified to make it look and feel like the other Mocha controls.  Still not done with it.  I want to move the buttons and pager into the header and footer of the windows and panel if it is in one.  The one that is there is functioning in the Demo of the develop branch.
