### ISSUE TITLE
No radius on maximize. 

### ISSUE THREAD

**Issue by cleankod** [cdotyone/mochaui#45]
Window, when maximized should have the shadow turned off.

**Comment by mui-org** [comment]
No shadow on maximize makes sense.
No radius on maximize, needs to be optional.

**Comment by cleankod** [comment]
I agree completely.

**Comment by mui-org** [comment]
Actually this ends up just being: no radius on maximize.  The shadow has little effect when window is maximized.

**Comment by cleankod** [comment]
I made some change and the window's height is 100% -minus dock's height. Thus making the shadow visible on the dock object.

**Comment by mui-org** [comment]
thanks, will look for this when doing GH-46

**Comment by mui-org** [comment]
also added - remove resize triangle when window is maximized
