### ISSUE TITLE
Window needs to stay below dock when maximized.

### ISSUE THREAD

**Issue by cleankod** [cdotyone/mochaui#46]
Window needs to stay below dock when maximized.

**Comment by eerne** [comment]
Isn't that indented behaviour?

**Comment by mui-org** [comment]
that is what I was thinking. are you asking for a fullscreen mode?

**Comment by cleankod** [comment]
No no. I am talking about the dock object to be always on top. Hence the maximized window should have height 100% minus the height of the dock.

**Comment by mui-org** [comment]
Yes agreed.  I have done this in my own version of Mocha before.  It should also use the options.restrict to determine if it does this or not.
