### ISSUE TITLE
String Method: parseQueryString

### ISSUE THREAD

**Issue by eerne** [cdotyone/mochaui#47]
MooTools More implements String.parseQueryString
http://mootools.net/docs/more/Native/String.QueryString#String:parseQueryString

Could we omit the MochaUI implementation?
http://github.com/cdotyone/mochaui/blob/develop/src/mui/core.js#L439

I haven't really found where in Mocha it is used.

**Comment by mui-org** [comment]
pull it

**Comment by eerne** [comment]
parseQueryString is only used in window.js to parse spacer.gif?from=fafafa&to=e5e5e5

removed it http://github.com/eerne/mochaui/commit/519c2383ae34113b336f8dfbda0d576f9dd9ba2e
