### ISSUE TITLE
IE6 error 'request' is null or not an object

### ISSUE THREAD

**Issue by eerne** [cdotyone/mochaui#48]
Hi
I noticed an error in IE6 'request' is null or not an object
line 215 src/demo/index.html
IE8 is ok. Can't test to IE7.

I tested back through all changes and found the error was introduced here:
http://github.com/cdotyone/mochaui/commit/1f35c6fd95e262e6b7a861f3a41703188ce86490

I went back commit by commit with git reset --hard HEAD^

This one should checkout the state with the commit where the error first appeared 
git reset --hard 1f35c6f

and going one more back git reset --hard HEAD^ should be a version without error.

I could get rid of the error introduced in HEAD 1f35c6f 
in 3 placed each marked with // Invisible dummy object 
options.somethingcolor that draws the dummy had undefined color

But I failed getting rid of the error in the current develop version.

**Comment by mui-org** [comment]
I do not have a machine configured to test IE6 right now.  I will have to create a VM to test it.  I needed to do this anyway.
