### ISSUE TITLE
MUI.Desktop full refactor

### ISSUE THREAD

**Issue by ghost** [cdotyone/mochaui#54]
#### No Markup

Want to be able to create MUI.Desktop without markup being loaded. 
Convert MUI.Desktop to class.
#### Class

Allow multiple Desktop instances with different columns and panels etc.
#### Lazy Load Alternate Desktops

Have it lazy load a different mocha-init set and clear current client window, and draw new desktop when requested.
#### Attached Dock

Needs to set MUI.dock with dock assigned to desktop when desktops change
#### New methods

MUI.Desktop.draw: adds desktop to dom
MUI.setDesktop('newdesktopname'): changes desktop.
#### New events

onDrawBegin
onDrawEnd
onDesktopUnload
onDesktopLoad
## Notes

See how MUI.Dock was converted to class.  Needs to be similar.

**Comment by cdotyone** [comment]
MUI.Desktop converted to class, need to add unload of desktops, so that you can manage multiple.  Currently should work with multiple, but no unload(cleanup).
