### ISSUE TITLE
MochaUI Instance Cleanup

### ISSUE THREAD

**Issue by ghost** [cdotyone/mochaui#55]
Close needs to remove instances of sub controls from MochaUI instance list.

When a control is closed or destroyed we need to clean them out of the MochaUI list.  Explicit or Garbage collection?

All instances should have an instance.el hash that has a list of all of the major control elements.

**Comment by cdotyone** [comment]
Chose explicit cleanup - windows and panels now cleanup sub controls.  Just need to get desktop and toolbars cleaning up and then this should be done.
