### ISSUE TITLE
Enhance - Content Update Mechanism

### ISSUE THREAD

**Issue by ghost** [cdotyone/mochaui#56]
#### JSON

Can process hierarchical or row data in json format.   Need to be able to convert row data to hierarchical on the client side.
#### Preprocessors

Plugin filters to process other formats besides json.  They will convert data to json to be passed to the controls.
#### Data Cache

Cache data from server in client.  generated keys and manual keys.  Allow flash storage??
#### Pagination

Needs to to be able to load data in chunks.  
#### Look Ahead

When pagination is turned on, need to be able to specify how many pages you want to pre-load for the user.
#### Common Interface

All controls in /Source/Controls need to be adjusted to use this DPM.

**Comment by eerne** [comment]
For Data Cache there is a nice library with uses different browser implementations and has cookie or flash fallback. http://github.com/jeremydurham/persist-js

**Comment by mui-org** [comment]
I am working on DPM now.  This needs to be completed before the Form Module

**Comment by mui-org** [comment]
Good call on the PersistJS.  Thanks I will use it.
