### ISSUE TITLE
IE8 - Latest Source

### ISSUE THREAD

**Issue by meglea** [cdotyone/mochaui#58]
I don't use IE a lot so I'm not sure how best to debug but I thought I would post what I just found.  perhaps you already are aware of this, but just in case here you go.

After installing and also appears in the latest "source" download:

ebpage error details

User Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; WOW64; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0)
Timestamp: Wed, 28 Jul 2010 05:08:47 UTC

Message: Invalid argument.
Line: 195
Char: 63
Code: 0
URI: http://layout.local/scripts/mootools-1.2.4-core-yc.js

:

**Comment by meglea** [comment]
Appears related to sections : in a panel.  If that logic is removed the page doesn't error.  I'll continue looking further.

**Comment by meglea** [comment]
How can I help with the "need verification"?

**Comment by meglea** [comment]
Okay so..using IE8 debugger it appears this is what it is complaining about in mootools core

this.style[b]=a;

**Comment by cdotyone** [comment]
sorry for the delay, I am now doing a debug for IE, and I confirmed this to be a problem.

**Comment by cdotyone** [comment]
This should good to go now.

**Comment by meglea** [comment]
Very good thank you.
