### ISSUE TITLE
Maximize window too large

### ISSUE THREAD

**Issue by axtg** [cdotyone/mochaui#60]
Hi,

Although I realize I brought this out over myself (the demonstration works perfect), I seem to have adjusted some width variable (could be padding, or margin as well), which causes a modal window to maximize just a little too far (the close window button falls of the screen).

Anyone who knows by heart where in the code I may have caused this?

**Comment by mui-org** [comment]
Sorry, for the delay getting back to you.  These questions are best served at 
http://groups.google.com/group/mocha-ui

Development branch?
