### ISSUE TITLE
Want to learn MUI.persist method

### ISSUE THREAD

**Issue by whitehorse5353** [cdotyone/mochaui#66]
when ever refresh the browser it goes to very fist page i want my last opened page...please help me out...i think if i use the persist it will get over i guess....

thanks by
Lokesh R

**Comment by cdotyone** [comment]
MUI.Persist is a general class.  It does not persist the entire interface.  Persistence of the entire MochaUI interface is a goal, but not completed yet.  This is dependent on the entire functionality being available through JSON (no html).  I could technically persist the html also, but not something I want to do.  MUI.Persist was put in place for when I complete the rest of the toolkit.  It is usable.  Look in /Tests/Core/Persist.json.  There are some unit tests in there.  You should be able to extract a useful test:function from there.

**Comment by whitehorse5353** [comment]
so this time no possibilities for persist the entire page in while refresh right ?

**Comment by mui-org** [comment]
not yet, but it will be once 1.0 is done.   check out issue 62.  cook left some code there to save workspaces.  might help you.  I have not given it a deep look yet though.
