### ISSUE TITLE
Desktop resize after column collapse needed when IFrame content is used

### ISSUE THREAD

**Issue by jellygnite** [cdotyone/mochaui#67]
When a column has iframe content and you collapse a column the iframe content does not adjust to fit the available space. I added 
MUI.Desktop.setDesktopSize();
to the columnCollapse and columnExpand functions. I also added it to 
window.addEvent('resize', function()
as the problem occurred if maximizing or restoring window size.

**Comment by mui-org** [comment]
version 0.9.7 or develop branch?

**Comment by jellygnite** [comment]
I was using version: '0.9.7'.

**Comment by eerne** [comment]
Fixed resizing of the iframe when a column is collapsed or resized. http://github.com/eerne/mochaui/commit/843f125a837ffe544eb44c33408b584cc504c58e
