### ISSUE TITLE
bug   firefox/chrome...

### ISSUE THREAD

**Issue by huwei1024** [cdotyone/mochaui#69]
Security error" code: "1000
 var myRules = mySheet.cssRules ? mySheet.cssRules : mySheet.rules; 

core.js    line 574

**Comment by cdotyone** [comment]
I have not seen this before.  Are you using stylesheets from different domains?  Please provide list of stylesheet tags in your html.  Please provide more detail in the future, this is to brief.

**Comment by huwei1024** [comment]
i'm using the 'develop' version. The core.js was not as same as old one.

new:
getCSSRule: function(selector) {
        for (var ii = 0; ii < document.styleSheets.length; ii++) {
            var mySheet = document.styleSheets[ii];
            var myRules = mySheet.cssRules ? mySheet.cssRules : mySheet.rules;
            for (var i = 0; i < myRules.length; i++) {
                if (myRules[i].selectorText == selector) {
                    return myRules[i];
                }
            }
        }
        return false;
    }

**Comment by cdotyone** [comment]
Are you hosting this from a web server, or straight from the file system?  My best guess given what you have said so far , you are using it straight from the file system.  Try from web server and see if it still happens.  Or copy the themes folder from /Source into /Demo and then update in core.js line 47 (latest version)
to:
themes:  'Themes/',

**Comment by huwei1024** [comment]
I download it again,and it works ok now.Thank you!
