### ISSUE TITLE
Modal (dialog) windows

### ISSUE THREAD

**Issue by cleankod** [cdotyone/mochaui#75]
I don't know if the name of these windows (issue title) is right but it would be great if there were windows behaving like this:
- Some action on window "A" opens window "B"
- You can't focus on window "A" before closing (choosing an option for instance) window "B".

**Comment by cdotyone** [comment]
This was handled already.  develop and develop-0.98 branches both have fix.  you can also find a quick patch at:
http://groups.google.com/group/mocha-ui/browse_thread/thread/ba314d25b15ce1d7?hl=en

look for post by me 'Oct 14, 7:28 pm'
