### ISSUE TITLE
Bottom dock bar problem

### ISSUE THREAD

**Issue by flmn** [cdotyone/mochaui#76]
In mochaui demo, at end of initializeWindows function, these is a line:MUI.parametricsWindow();

This line of code open a para metrics window when web page loaded.

But, if we don't open any window at startup, the dock bar will overlap panels above it. When we collapse left bottom panel, the panel header will go behind dock bar.

Besides open a window at startup, turn dock bar auto hide on and off can make dock bar works as normal.

**Comment by cdotyone** [comment]
in /Source/Core/Desktop.js

change line 59 from

if (!this.dock) this.setDesktopSize();

to:
this.setDesktopSize();

I still need to track down why two calls to desktop size are needed, but not important enough to hold up for now.

**Comment by flmn** [comment]
I add this line "MUI.desktop.setDesktopSize();" after "MUI.Desktop.initialize();", it works.

Waiting for a  to solve this problem.

**Comment by cdotyone** [comment]
This appears to be working in the current 1.0 develop branch.
