### ISSUE TITLE
Safari doesn't like class + missing image

### ISSUE THREAD

**Issue by eerne** [cdotyone/mochaui#80]
This fixes Safari:
https://github.com/eerne/mochaui/commit/217d44a8754880223f12bb9a13a28ca385db6ab8

Not sure about should it be toolbar or toolbox, anyway this fixes the 404 image not found:
https://github.com/eerne/mochaui/commit/651ce452a32eab0f04f95ab0bea04a90e4c136a2

**Comment by mui-org** [comment]
I changed image name in themes to toolbar.  I am still working in this area, so expect more problems surrounding toolbars.  Thanks for the fixes.
