### ISSUE TITLE
new MUI.Window causes to hide immediately

### ISSUE THREAD

**Issue by dennisvandenende** [cdotyone/mochaui#81]
Hi Chris,
on the latest branch there seems to be something wrong with the "new MUI.Window"
The new created window is hidden immediately. 
The reason is because in window.js you have a hideSpinner as also in core.js. Because the "new MUI.Window" calls content.js, the system uses core.js to activate hideSpinner.
around line 369 you wrote: if (count <= 1) this.hide();
This calls the "hide" within the window.js and NOT core.js

quick solution:
    if (count <= 1) this.setStyle('display', 'none'); //this.hide();

I miss the time to check what youre intentions are with this, maybe you see it.

**Comment by cdotyone** [comment]
The element now has instance attached to it.  The .hide() picked that up sent close to the instance instead of the spinner DOM element.

Thanks is has been patched now.
