### ISSUE TITLE
Panel drag clone experimental

### ISSUE THREAD

**Issue by eerne** [cdotyone/mochaui#84]
Please test https://github.com/eerne/mochaui/tree/drag-clone :)

**Comment by cdotyone** [comment]
Pretty cool. 

I found two things using Firefox (may be happening on other browsers).  
1. When panel is dropped it is not resized to fit the new column it is placed in.  
2. You should not be able to drag the last panel in a column.  It leaves a blank space if you do.  You could close the empty column, but the user has no way of creating a new column.  May be confusing.

**Comment by eerne** [comment]
Did you fix 1. ? I couldn't reproduce it, but probably because I already pulled your fix.

About no 2. Actually I don't mind having an empty column. I'm thinking in a situation where there are many columns and panels and you want to reorganize the panels. It should be possible to drag them around until everything is in place and it's natural to me if you drag the last panel in a column, then it's empty. This leaves room to drag another panel back inside (see http://www.bbc.co.uk/). 

The only minor thing bothering me is that an empty column is 100% white it should be gray-ish, at least same as the panel background or darker?

Creating a new column should be possible. Maybe a little [+] button somewhere or a menu item "View / Add a column"
    var sideColumnCount = 2;
    sideColumnCount++;
    new MUI.Column({
        id: 'sideColumn' + sideColumnCount,
        placement: 'right',
        width: 220,
        resizeLimit: [200, 300]
    });
This adds a new empty column but as long as there is no panel inside it won't have the correct height…

**Comment by cdotyone** [comment]
Yes fixed the panel size issue, don't know if it is still fixed after my last push.  I will check. 

#2.   I don't really care if it allows blank columns.  I agree on the color. I will see about the column height problem.  I am also cool with creating a way to add column.   I think I prefer the menu option, but I am open to something else.
