### ISSUE TITLE
Window shake on Google Chrome

### ISSUE THREAD

**Issue by cleankod** [cdotyone/mochaui#86]
The shake does not work anymore After Google Chrome has been updated to version 8.x  (can't remember which version).

**Comment by cdotyone** [comment]
works in version 9.x

**Comment by cleankod** [comment]
I have updated my Chrome browser to 9.x and went to mochaui.org/demo - it does not work. Is it fixed on development branch?

**Comment by cdotyone** [comment]
it is working on my development branch
