### ISSUE TITLE
Regexp (getTitle) is eating uppercase S

### ISSUE THREAD

**Issue by cleankod** [cdotyone/mochaui#88]
When a title of response is like this:
    <title>Strony nie znaleziono</title>
which is the usual Polish Error_404 message, the regexp:
    var getTitle = new RegExp('<title>[\n\r\s]_(._)[\n\r\s]*</title>', 'gmi');
leaves me with:
    trony nie znaleziono

**Comment by cdotyone** [comment]
Replace with '<title>[\n\r\s]_(._)[\n\r\s]*</title>'

Need to escape the \s

Branches develop and develop-0.9.8 branches patched
