### ISSUE TITLE
Getting controls by group

### ISSUE THREAD

**Issue by cleankod** [cdotyone/mochaui#93]
Updating and reloading controls by ID is great but when it comes to reload more than one control, it's getting strange.

It would be great if controls could have groups which can be accessed from. It that case reloading a couple of element would be safer (the control exists, etc.).

I find it useful when I want to reload grids, after adding/deleting/update something.

**Comment by cdotyone** [comment]
Need to think on this.  Do you have any API method examples?  Will it be triggered off a result from server?  What would that look like?  Give me some ideas to work with and we will see what we can do.

**Comment by cdotyone** [comment]
No update to this, so closing.
-Chris
